### ISSUE TITLE
CurrentPageNumber and TotalPageNumber

### ISSUE THREAD

**Issue by ImBeCiliC** [rokebrand/react-native-twig#1]
Is there a possibility to expose these variables to be used in the twig template?

**Comment by rokebrand** [comment]
The print templates do not include the page numbers, however you can manage the page numbers and their styles through your print @page styles.

https://developer.mozilla.org/en-US/docs/Web/CSS/@page

@page {
  /* margin box at top right showing page number */
  @top-right {
    content: "Page " counter(pageNumber);
  }
}

If you need more control you can use https://pagedjs.org/ to split up your pages and then have full control of your pages before they are printed, this uses your print page styles too.
